[2020-08-06 17:19:41.415742] [INFO] [handle_init.py] [get_value] [27] 获取配置文件的值，node：dbconfig,key：db_config, data：{"host":"127.0.0.1","port":3306,"user":"root","password":"123456","database":"mytest","charset":"utf8"}
[2020-08-06 17:19:41.434692] [ERROR] [handle_db.py] [connectiondatabase] [30] connectDatabase failed
[2020-08-06 17:20:17.753480] [INFO] [handle_init.py] [get_value] [27] 获取配置文件的值，node：dbconfig,key：db_config, data：{"host":"127.0.0.1","port":3306,"user":"root","password":"123456","database":"mytest","charset":"utf8"}
[2020-08-06 17:20:17.759464] [ERROR] [handle_db.py] [connectiondatabase] [30] connectDatabase failed
[2020-08-06 17:20:57.680133] [INFO] [handle_init.py] [get_value] [27] 获取配置文件的值，node：dbconfig,key：db_config, data：{"host":"127.0.0.1","port":3306,"user":"root","password":"123456","database":"mytest","charset":"utf8"}
[2020-08-06 17:20:57.686087] [ERROR] [handle_db.py] [connectiondatabase] [30] connectDatabase failed
[2020-08-06 17:27:00.541249] [INFO] [handle_init.py] [get_value] [27] 获取配置文件的值，node：dbconfig,key：db_config, data：{"host":"127.0.0.1","port":3306,"user":"root","password":"123456","database":"mytest","charset":"utf8"}
[2020-08-06 17:27:00.547233] [ERROR] [handle_db.py] [connectiondatabase] [30] connectDatabase failed
[2020-08-06 17:27:11.544593] [INFO] [handle_init.py] [get_value] [27] 获取配置文件的值，node：dbconfig,key：db_config, data：{"host":"127.0.0.1","port":3306,"user":"root","password":"123456","database":"mytest","charset":"utf8"}
[2020-08-06 17:27:11.559554] [ERROR] [handle_db.py] [connectiondatabase] [30] connectDatabase failed
